name: Workflow_02

on: 
    workflow_run:
        workflows: ["Workflow_01"]
        types:
          - completed
jobs: 
    update-readme-with-blog: 
        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "4"
                feed_list: "https://medium.com/feed/@irfankaraman"
