name: Workflow_02

on: 
    workflow_run:
        workflows: ["Workflow_01"]
        types:
          - completed
jobs: 
    update-readme-with-blog: 
        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v2
